version: 2
updates:
  # Keep npm dependencies updated
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'

  # Keep GitHub actions dependencies updated
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    labels:
      - 'github-actions'
      - 'dependencies'
