version: '3.8'
services:
  postgres:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=localdb
      - POSTGRES_PASSWORD=Secret1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
